# SPDX-FileCopyrightText: 2022 Uwe Fechner
# SPDX-License-Identifier: MIT

# DO NOT EDIT THIS FILE
# This file was generated by src/build.jl
# Edit src/sysstate.yaml instead

"""
    SysState{P, O, K, D, L, W, T, S, N, F}

Basic system state. One of these is saved per time step. P is the number
of position slots, O the number of oriented frames, K how many of those are wings,
D the number of twist surfaces, L the number of pulleys, W the number of winches,
T the number of tethers, S the number of segments, N the number of aerodynamic
panels and F the float type of every non-integer field. No field is a fixed length:
a model with five winches or ten twist surfaces logs all of them.

The O oriented frames are the K wings first, then the `O - K` bodies: `Qw/Qx/Qy/Qz`
and `turn_rate_x/y/z` hold wing `k` at `k` and body `b` at `K + b`, and frame 1 is
the kite, aliased by the `orient` property. Positions and velocities hold the points
first and the O frames in their last O slots, wings then bodies. [`wing_Q`](@ref),
[`body_Q`](@ref), [`wing_pos`](@ref) and [`body_pos`](@ref) index by those offsets.

A `_KA` quantity at `k` is in the frame `Q[k]`: `aero_force_KA_x[k]` is a component
of wing k's force in the frame that `Qw/Qx/Qy/Qz[k]` rotates into ENU. The properties
`aero_force_KA` and `aero_moment_KA` are wing 1's loads as a mutable 3-vector. The turn
rates are `KA` too, and every other vector is ENU.

Together `X/Y/Z`, `VX/VY/VZ`, `Qw/Qx/Qy/Qz`, `turn_rate_x/y/z`,
`twist_angles`, `twist_vel`, `pulley_len`, `pulley_vel`, `l_tether` and
`v_reelout` hold a complete differential state, so a single row can be
used to restart a simulation. `flap_angle` is a derived deflection, not
part of that state, and neither are the `aero_force_*`, `drag_force_*`,
`spring_force` and `gamma_distribution` loads, which are logged for inspection.

$(TYPEDFIELDS)
"""
@with_kw_noshow mutable struct SysState{P, O, K, D, L, W, T, S, N, F}
    "time since start of simulation [s]"
    time::Float64 = 0
    "time needed for one simulation timestep [s]"
    t_sim::Float64 = 0
    "state of system state control"
    sys_state::Int16 = 0
    "cycle number"
    cycle::Int16 = 0
    "number of the figure of eight of the current cycle"
    fig_8::Int16 = 0
    "mechanical energy [Wh]"
    e_mech::Float64 = 0
    "KA quaternion w-component, one per wing then body (frame 1 = kite)"
    Qw::MVector{O, F} = ones(F, O)
    "KA quaternion x-component, one per wing then body"
    Qx::MVector{O, F} = zeros(F, O)
    "KA quaternion y-component, one per wing then body"
    Qy::MVector{O, F} = zeros(F, O)
    "KA quaternion z-component, one per wing then body"
    Qz::MVector{O, F} = zeros(F, O)
    "turn rates around the KA body x, y and z axis [rad/s]"
    turn_rates::MVector{3, F} = zeros(F, 3)
    "elevation angle [rad]"
    elevation::F = 0
    "azimuth angle in wind reference frame [rad]"
    azimuth::F = 0
    "azimuth rate [rad/s]"
    azimuth_rate::F = 0
    "tether length, one per tether [m]"
    l_tether::MVector{T, F} = zeros(F, T)
    "reelout speed, one per winch [m/s]"
    v_reelout::MVector{W, F} = zeros(F, W)
    "tether force at the winch, one per winch [N]"
    winch_force::MVector{W, F} = zeros(F, W)
    "depower settings [0..1]"
    depower::F = 0
    "actual steering [-1..1]"
    steering::F = 0
    "steering after the kcu, before applying offset and depower scaling [-1..1]"
    kcu_steering::F = 0
    "set value of the steering [-1..1]"
    set_steering::F = 0
    "heading angle [rad]"
    heading::F = 0
    "heading rate [rad/s]"
    heading_rate::F = 0
    "course angle [rad]"
    course::F = 0
    "bearing angle (set value of heading/ course) [rad]"
    bearing::F = 0
    "attractor coordinates (azimuth, elevation) [rad]"
    attractor::MVector{2, F} = zeros(F, 2)
    "norm of apparent wind speed [m/s]"
    v_app::F = 0
    "wind vector at reference height [m/s]"
    v_wind_gnd::MVector{3, F} = zeros(F, 3)
    "wind vector at 200m height [m/s]"
    v_wind_200m::MVector{3, F} = zeros(F, 3)
    "wind vector at the height of the kite [m/s]"
    v_wind_kite::MVector{3, F} = zeros(F, 3)
    "angle of attack [rad]"
    AoA::F = 0
    "side slip angle [rad]"
    side_slip::F = 0
    "angle of attack at particle C [rad]"
    alpha3::F = 0
    "angle of attack at particle D [rad]"
    alpha4::F = 0
    "lift coefficient"
    CL2::F = 0
    "drag coefficient"
    CD2::F = 0
    "aerodynamic force along KA x, one per wing [N]"
    aero_force_KA_x::MVector{K, F} = zeros(F, K)
    "aerodynamic force along KA y, one per wing [N]"
    aero_force_KA_y::MVector{K, F} = zeros(F, K)
    "aerodynamic force along KA z, one per wing [N]"
    aero_force_KA_z::MVector{K, F} = zeros(F, K)
    "aerodynamic moment around KA x, one per wing [Nm]"
    aero_moment_KA_x::MVector{K, F} = zeros(F, K)
    "aerodynamic moment around KA y, one per wing [Nm]"
    aero_moment_KA_y::MVector{K, F} = zeros(F, K)
    "aerodynamic moment around KA z, one per wing [Nm]"
    aero_moment_KA_z::MVector{K, F} = zeros(F, K)
    "twist angle, one per twist_surface [rad]"
    twist_angles::MVector{D, F} = zeros(F, D)
    "velocity vector of the kite [m/s]"
    vel_kite::MVector{3, F} = zeros(F, 3)
    "acceleration [m/s²]"
    acc::F = 0
    "position in x; points first, the last O wings then bodies [m]"
    X::MVector{P, F} = zeros(F, P)
    "position in y; points first, the last O wings then bodies [m]"
    Y::MVector{P, F} = zeros(F, P)
    "position in z; points first, the last O wings then bodies [m]"
    Z::MVector{P, F} = zeros(F, P)
    "flap deflection per aero segment, one per twist_surface [rad]"
    flap_angle::MVector{D, F} = zeros(F, D)
    "velocity in x; points first, the last O wings then bodies [m/s]"
    VX::MVector{P, F} = zeros(F, P)
    "velocity in y; points first, the last O wings then bodies [m/s]"
    VY::MVector{P, F} = zeros(F, P)
    "velocity in z; points first, the last O wings then bodies [m/s]"
    VZ::MVector{P, F} = zeros(F, P)
    "aerodynamic force on each point in x, ENU reference frame [N]"
    aero_force_x::MVector{P, F} = zeros(F, P)
    "aerodynamic force on each point in y, ENU reference frame [N]"
    aero_force_y::MVector{P, F} = zeros(F, P)
    "aerodynamic force on each point in z, ENU reference frame [N]"
    aero_force_z::MVector{P, F} = zeros(F, P)
    "drag force on each point in x, ENU reference frame [N]"
    drag_force_x::MVector{P, F} = zeros(F, P)
    "drag force on each point in y, ENU reference frame [N]"
    drag_force_y::MVector{P, F} = zeros(F, P)
    "drag force on each point in z, ENU reference frame [N]"
    drag_force_z::MVector{P, F} = zeros(F, P)
    "spring force, one per segment [N]"
    spring_force::MVector{S, F} = zeros(F, S)
    "circulation, one per aerodynamic panel [m²/s]"
    gamma_distribution::MVector{N, F} = zeros(F, N)
    "KA turn rate around x, one per wing then body [rad/s]"
    turn_rate_x::MVector{O, F} = zeros(F, O)
    "KA turn rate around y, one per wing then body [rad/s]"
    turn_rate_y::MVector{O, F} = zeros(F, O)
    "KA turn rate around z, one per wing then body [rad/s]"
    turn_rate_z::MVector{O, F} = zeros(F, O)
    "twist rate, one per twist_surface [rad/s]"
    twist_vel::MVector{D, F} = zeros(F, D)
    "length of the first leg of each pulley [m]"
    pulley_len::MVector{L, F} = zeros(F, L)
    "rate of change of pulley_len [m/s]"
    pulley_vel::MVector{L, F} = zeros(F, L)
    "torque setting, one per winch [Nm]"
    set_torque::MVector{W, F} = zeros(F, W)
    "speed setting, one per winch [m/s]"
    set_speed::MVector{W, F} = zeros(F, W)
    "force setting, one per winch [N]"
    set_force::MVector{W, F} = zeros(F, W)
    "external force applied to each point in x, ENU reference frame [N]"
    set_ext_force_x::MVector{P, F} = zeros(F, P)
    "external force applied to each point in y, ENU reference frame [N]"
    set_ext_force_y::MVector{P, F} = zeros(F, P)
    "external force applied to each point in z, ENU reference frame [N]"
    set_ext_force_z::MVector{P, F} = zeros(F, P)
    "generic variable 01"
    var_01::F = 0
    "generic variable 02"
    var_02::F = 0
    "generic variable 03"
    var_03::F = 0
    "generic variable 04"
    var_04::F = 0
    "generic variable 05"
    var_05::F = 0
    "generic variable 06"
    var_06::F = 0
    "generic variable 07"
    var_07::F = 0
    "generic variable 08"
    var_08::F = 0
    "generic variable 09"
    var_09::F = 0
    "generic variable 10"
    var_10::F = 0
    "generic variable 11"
    var_11::F = 0
    "generic variable 12"
    var_12::F = 0
    "generic variable 13"
    var_13::F = 0
    "generic variable 14"
    var_14::F = 0
    "generic variable 15"
    var_15::F = 0
    "generic variable 16"
    var_16::F = 0
    @assert K <= O "a SysState of $O oriented frames cannot hold $K wings"
end
