# SPDX-FileCopyrightText: 2022 Uwe Fechner
# SPDX-License-Identifier: MIT

# Script to create the files _sysstate.jl, _show.jl, _demo_syslog.jl, _logger.jl, _log.jl, 
# _syslog.jl and _load_log.jl from the file sysstate.yaml.  
using YAML, OrderedCollections

include("yaml_utils.jl")

COMMENT="""
# SPDX-FileCopyrightText: 2022 Uwe Fechner
# SPDX-License-Identifier: MIT

# DO NOT EDIT THIS FILE
# This file was generated by src/build.jl
# Edit src/sysstate.yaml instead

"""
"""Type of a `sysstate.yaml` field in the generated struct, with `MyFloat` as `F`."""
generic_type(spec) = replace(spec, "MyFloat" => "F")

"""Type of a `sysstate.yaml` field with `MyFloat` resolved to the package default."""
concrete_type(spec) = spec

"""Length parameter of an `MVector` field spec, or `nothing` for a scalar."""
function vector_length(spec)
    matched = match(r"^MVector\{(\w+), ", spec)
    isnothing(matched) ? nothing : matched.captures[1]
end

"""Default initialiser for a field, as written into the generated struct."""
function field_default(key, spec, eltype_name)
    len = vector_length(spec)
    isnothing(len) && return "= 0"
    # Qw defaults to ones so the default frame is the identity quaternion.
    key == "Qw" && return "= ones(" * eltype_name * ", " * len * ")"
    return "= zeros(" * eltype_name * ", " * len * ")"
end

HEADER = """
\"\"\"
    SysState{P, O, K, D, L, W, T, S, N, F}

Basic system state. One of these is saved per time step. P is the number
of position slots, O the number of oriented frames, K how many of those are wings,
D the number of twist surfaces, L the number of pulleys, W the number of winches,
T the number of tethers, S the number of segments, N the number of aerodynamic
panels and F the float type of every non-integer field. No field is a fixed length:
a model with five winches or ten twist surfaces logs all of them.

The O oriented frames are the K wings first, then the `O - K` bodies: `Qw/Qx/Qy/Qz`
and `turn_rate_x/y/z` hold wing `k` at `k` and body `b` at `K + b`, and frame 1 is
the kite, aliased by the `orient` property. Positions and velocities hold the points
first and the O frames in their last O slots, wings then bodies. [`wing_Q`](@ref),
[`body_Q`](@ref), [`wing_pos`](@ref) and [`body_pos`](@ref) index by those offsets.

A `_KA` quantity at `k` is in the frame `Q[k]`: `aero_force_KA_x[k]` is a component
of wing k's force in the frame that `Qw/Qx/Qy/Qz[k]` rotates into ENU. The properties
`aero_force_KA` and `aero_moment_KA` are wing 1's loads as a mutable 3-vector. The turn
rates are `KA` too, and every other vector is ENU.

Together `X/Y/Z`, `VX/VY/VZ`, `Qw/Qx/Qy/Qz`, `turn_rate_x/y/z`,
`twist_angles`, `twist_vel`, `pulley_len`, `pulley_vel`, `l_tether` and
`v_reelout` hold a complete differential state, so a single row can be
used to restart a simulation. `flap_angle` is a derived deflection, not
part of that state, and neither are the `aero_force_*`, `drag_force_*`,
`spring_force` and `gamma_distribution` loads, which are logged for inspection.

\$(TYPEDFIELDS)
\"\"\"
@with_kw_noshow mutable struct SysState{P, O, K, D, L, W, T, S, N, F}"""
FOOTER = """    @assert K <= O "a SysState of \$O oriented frames cannot hold \$K wings"
end"""
inputfile = joinpath("src", "sysstate.yaml")
outputfile = joinpath("src", "_sysstate.jl")
outputfile2 = joinpath("src", "_show.jl")
outputfile3 = joinpath("src", "_demo_syslog.jl")
outputfile4 = joinpath("src", "_logger.jl")
outputfile5 = joinpath("src", "_log.jl")
outputfile6 = joinpath("src", "_syslog.jl")
outputfile7 = joinpath("src", "_load_log.jl")

# read the file sysstate.yaml
sysstate = YAML.load_file(inputfile, dicttype=OrderedDict{String,Any})["sysstate"]
lines = readfile(inputfile)
open(outputfile,"w") do io
    print(io, COMMENT)
    println(io, HEADER)
    for key in keys(sysstate)
        comment = get_comment(lines, key)
        println(io, "    " * comment)
        spec = generic_type(sysstate[key])
        println(io, "    " * key * "::" * spec * " " *
            field_default(key, sysstate[key], "F"))
    end
    println(io, FOOTER)
end
HEADER = "function Base.show(io::IO, st::SysState)" 
open(outputfile2,"w") do io
    print(io, COMMENT)
    println(io, HEADER)
    for key in keys(sysstate)
        if key == "Qw"
            # Show the legacy single `orient` (frame 1); hide the raw components.
            description = rpad("orient [-]:", 19, " ")
            println(io, "    println(io, \"" * description *
                "\", MVector{4}(st.orient))")
        elseif key in ("Qx", "Qy", "Qz")
            continue  # merged into the orient line above
        else
            unit = get_unit(lines, key)
            description = rpad(key * " " * unit * ":", 19, " ")
            println(io, "    println(io, \"" * description * "\", st." * key * ")")
        end
    end
    println(io, "end")
end
HEADER = """
\"\"\"
    demo_syslog(P, O=1, K=1, D=0, L=0, W=1, T=W, S=0, N=0; duration=10)

Create a demo flight log with given duration [s] as StructArray of
`SysState{P, O, K, D, L, W, T, S, N, MyFloat}`, the counts meaning what they mean there.
The demo data fills the points and frame 1; every other entry is zero.
\"\"\"
function demo_syslog(P, O=1, K=1, D=0, L=0, W=1, T=W, S=0, N=0; duration=10)
    max_height = 6.03
    steps   = Int(duration * se().sample_freq) + 1
"""
open(outputfile3,"w") do io
    print(io, COMMENT)
    print(io, HEADER)
    for key in keys(sysstate)
        println(io, "    " * key * "_vec = Vector{" * sysstate[key] * "}(undef, steps)")
    end
    println(io, "    for i in range(0, length=steps)")
    println(io, "        state = demo_state(P, max_height * i/steps, i/se().sample_freq;")
    println(io, "            wings=K, bodies=O-K, deflections=D, pulleys=L, winches=W,")
    println(io, "            tethers=T, segments=S, panels=N)")
    println(io, "        elevation_vec[i+1] = asin(state.Z[end]/state.X[end])")
    for key in keys(sysstate)
        println(io, "        " * key * "_vec[i+1] = state." * key)
    end
    println(io, "    end")
    print(io, "    StructArray{SysState{P, O, K, D, L, W, T, S, N, MyFloat}}((")
    for (i, key) in pairs(collect(keys(sysstate)))
        if i == length(keys(sysstate))
            print(io, key * "_vec")
        else
            print(io, key * "_vec, ")
        end
        if i % 6 == 0
            print(io, "\n" * " " ^ 30)   
        end
    end
    println(io, "))")
    println(io, "end")
end
HEADER = """
\"\"\"
    mutable struct Logger{P, O, K, D, L, W, T, S, N, F, Q}

Struct to store a simulation log. P, O, K, D, L, W, T, S, N and F are the counts
and float type of the [`SysState`](@ref) it logs, and Q is the number of time steps
that will be pre-allocated.

Constructor:
- Logger(P, steps; wings, bodies, deflections, pulleys, winches, tethers, segments,
  panels, precision)

Fields:

\$(TYPEDFIELDS)
\"\"\"
@with_kw mutable struct Logger{P, O, K, D, L, W, T, S, N, F, Q}
    points::Int64 = P
    orients::Int64 = O
    wings::Int64 = K
    deflections::Int64 = D
    pulleys::Int64 = L
    winches::Int64 = W
    tethers::Int64 = T
    segments::Int64 = S
    panels::Int64 = N
    index::Int64 = 1
    "date and time the logger was created, local time as ISO 8601"
    created::String = Libc.strftime("%Y-%m-%dT%H:%M:%S", time())
"""
open(outputfile4,"w") do io
    print(io, COMMENT)
    print(io, HEADER)
    for key in keys(sysstate)
        spec = generic_type(sysstate[key])
        if isnothing(vector_length(sysstate[key]))
            println(io, "    " * key * "_vec::Vector{" * spec * "} = zeros(" * spec * ", Q)")
        else
            println(io, "    " * key * "_vec::Vector{" * spec * "} = [zero(" * spec * ") for _ in 1:Q]")
        end
    end
    println(io, "end")
end
HEADER = """
\"\"\"
    log!(logger::Logger, state::SysState)

Log a state in a logger object. Do nothing if the preallocated size would be exceeded.
Returns the current number of elements of the log.
\"\"\"
function log!(logger::Logger, state::SysState)
    i = logger.index
    if i > length(logger.time_vec)
        return length(logger.time_vec)
    end
"""
open(outputfile5,"w") do io
    print(io, COMMENT)
    print(io, HEADER)
    for key in keys(sysstate)
        if startswith(sysstate[key], "MVector")
            println(io, "    logger." * key * "_vec[i] .= state." * key)
        else
            println(io, "    logger." * key * "_vec[i] = state." * key)
        end
    end
    println(io, "    logger.index+=1")
    println(io, "    return i")
    println(io, "end")
end
COLMETA_HEADER = """
\"\"\"
    default_colmeta()

The column metadata of a log whose caller named none: each of the free columns
`var_01` to `var_16` displayed under its own name.
\"\"\"
default_colmeta() = Dict("""
SYSLOG_HEADER = """

\"\"\"
    syslog(logger::Logger)

The rows that were logged, as a `StructArray` of `SysState`. It is a view on the
columns of `logger`, so the steps it has room for but never logged are left out
and the logger stays usable.
\"\"\"
function syslog(logger::Logger{P, O, K, D, L, W, T, S, N, F, Q}
                ) where {P, O, K, D, L, W, T, S, N, F, Q}
    l = logger
    preallocated = StructArray{SysState{P, O, K, D, L, W, T, S, N, F}}((
        """
open(outputfile6,"w") do io
    print(io, COMMENT)
    print(io, COLMETA_HEADER)
    var_keys = [key for key in keys(sysstate) if startswith(key, "var_")]
    for (i, key) in pairs(var_keys)
        print(io, ":" * key * " => [\"name\" => \"" * key * "\"]")
        println(io, i == length(var_keys) ? ")" : ",")
        i == length(var_keys) || print(io, " " ^ 25)
    end
    print(io, SYSLOG_HEADER)
    for (i, key) in pairs(collect(keys(sysstate)))
        print(io, "l." * key * "_vec")
        if i < length(keys(sysstate))
            print(io, i % 3 == 0 ? ",\n" * " " ^ 8 : ", ")
        end
    end
    println(io, "))")
    println(io, "    view(preallocated, 1:length(logger))")
    println(io, "end")
end
HEADER = """
\"\"\"
    load_log(filename::String; path="")

Read a log file that was saved as .arrow file.
\"\"\"
load_log(P, filename::String) = load_log(filename)
function load_log(filename::String; path="")
    if path == ""
        path = DATA_PATH[1]
    end
    fullname = filename
    if ! isfile(filename)
        if isnothing(findlast(isequal('.'), filename))
            fullname = joinpath(path, basename(filename)) * ".arrow"
        else
            fullname = joinpath(path, basename(filename)) 
        end
    end
    table   = Arrow.Table(fullname)
    P =  length(table.Z[1])
    O =  length(table.Qw[1])
    D =  haskey(table, :flap_angle) ? length(table.flap_angle[1]) : 0
    L =  haskey(table, :pulley_len) ? length(table.pulley_len[1]) : 0
    T =  eltype(table.Z[1])
    colmeta = Dict(:var_01=>Arrow.getmetadata(table.var_01)["name"],
                   :var_02=>Arrow.getmetadata(table.var_02)["name"],
                   :var_03=>Arrow.getmetadata(table.var_03)["name"],
                   :var_04=>Arrow.getmetadata(table.var_04)["name"],
                   :var_05=>Arrow.getmetadata(table.var_05)["name"],
                   :var_06=>Arrow.getmetadata(table.var_06)["name"],
                   :var_07=>Arrow.getmetadata(table.var_07)["name"],
                   :var_08=>Arrow.getmetadata(table.var_08)["name"],
                   :var_09=>Arrow.getmetadata(table.var_09)["name"],
                   :var_10=>Arrow.getmetadata(table.var_10)["name"],
                   :var_11=>Arrow.getmetadata(table.var_11)["name"],
                   :var_12=>Arrow.getmetadata(table.var_12)["name"],
                   :var_13=>Arrow.getmetadata(table.var_13)["name"],
                   :var_14=>Arrow.getmetadata(table.var_14)["name"],
                   :var_15=>Arrow.getmetadata(table.var_15)["name"],
                   :var_16=>Arrow.getmetadata(table.var_16)["name"],
    )
    # example_metadata = KiteUtils.Arrow.getmetadata(table.var_01)
    syslog = StructArray{SysState{P, O, K, D, L, W, T, S, N, F}}(("""
open(outputfile7,"w") do io
    print(io, COMMENT)
    print(io, HEADER)
    for (i, key) in pairs(collect(keys(sysstate)))
        if i == length(keys(sysstate))
            print(io, "table." * key)
        else
            print(io, "table." * key * ", ")
        end
        if i % 5 == 0
            print(io, "\n" * " " ^ 39)   
        end
    end
    println(io, "))")
    println(io, "    return SysLog{P}(basename(fullname[1:end-6]), colmeta, syslog)")
    println(io, "end")
end
